### ISSUE TITLE
Rotary Encoder issue

### ISSUE THREAD

**Issue by ator1811** [simplefoc/Arduino-FOC-dcmotor#6]
Hi 

I did some tests with the latest version of the DCmotor Repo. I use a ATMEGA 2560. I found 2 issue's:

1. The example script of the dc-open-loop does not compile. Refs to library and the motor class is wrong
```
#include "SimpleFOCDCMotor.h" //This must be #include "SimpleDCMotor.h" I think
// DCDriver object - this is the only thing needed for open-loop control.
// There are different types to choose from, please select the correct one
// that matches your motor driver hardware.
DCDriverSpeedDir driver = DCDriverSpeedDir(2, 3); \\??
```

2. I tested with a rotary encoder into the dc-position and dc-velocity example scripts. It does compile. After entering a value the motor start spinning until it reaches the max voltage. In the monitoring output the 2 column on the right remains zero (no readout of the Rotary encoders). I tested the encoders separate with another SimpleFoc script and they are working fine. Also the callibration is skipped. Debug output:
```
MOT: Init
MOT: Enable driver.
MOT: Monitor enabled!
```
(no calibration)

Monitoring output (target 5,0)
```
5.0000	3.3387	0.0000	0.0000
5.0000	3.3455	0.0000	0.0000
5.0000	3.3524	0.0000	0.0000
5.0000	3.3593	0.0000	0.0000
5.0000	3.3661	0.0000	0.0000
```

If you have any questions please let me know
Regards

**Comment by runger1101001** [comment]
Thank you for your tests and your error report! I am sorry you are having troubles.

Regarding the example, this has been fixed and will be in the next release.

Regarding the rotary encoder, think it is a different problem. The DCMotor calls the sensor.update() method, so if the sensor is linked to the motor and correctly initialised, then it will work. I think there must be a different problem regarding the sensor initialisation.

Regarding the calibration, DC motors don't need a motor calibration, but we are also skipping the sensor index search. We should add this in a future version of the library. I will make a separate issue for this.

**Comment by ator1811** [comment]
Thx. Regarding the encoder. I also had the problem with I2C and SPI sensors. Hapily, yesterday I found this discussion https://community.simplefoc.com/t/simpledc-problem/3980/8. The solution was to add `motor.sensor_direction = Direction::CW;`. That did the trick.  In the same discussion is was mentioned that `driver.pwm_frequency = 5000;` in setup is missing in some examples.

**Comment by runger1101001** [comment]
Thanks for the feedback! I'm glad you solved your problem, and if it is ok I will close this issue.

Regarding the pwm_frequency, maybe I will add it to more examples, but it's really a matter of user choice and the driver used, some drivers can work with much faster frequencies. Ideally you want the frequency to be > 24kHz, so it is not in the audible range. Then the solution will be more quiet.
